---
# task used to install a single rust crate from crates.io
- name: rust-install-crate | cargo install "{{ item }}"  # noqa name[casing]
  ansible.builtin.shell: |
    cargo install --locked --all-features "{{ item }}" || cargo install "{{ item }}"
  register: output
  changed_when: not "Ignored package" in output.stdout
