---
# task used to install a single rust crate
- name: rust-install-crate | "cargo install {{ item }}"
  ansible.builtin.shell: |
    cargo install --locked "{{ item }}" || cargo install "{{ item }}"
  register: output
  changed_when: not "Ignored package" in output.stdout
