---
# task used to install a single rust crate via git repo
- name: rust-install-crate-via-git | cargo install --git "{{ item.url }} {{ item.binaries }} {{ item.extra_flags }}"  # noqa name[casing] name[template]
  ignore_errors: "{{ item.failure_ok | default(false) }}"
  ansible.builtin.shell: |
    printf "url: %s\n" "{{ item.url }}"
    printf "binaries: %s\n" "{{ item.binaries }}"
    source /etc/profile.d/nix.sh
    set -x
    cargo install --git "{{ item.url }}" "{{ item.binaries }}" $(printf "%s " "{{ item.extra_flags }}") ||
      cargo install --git "{{ item.url }}" "{{ item.binaries }}" $(printf "%s " "{{ item.extra_flags }}") --locked
  register: output
  changed_when: not "Ignored package" in output.stdout
