#!/usr/bin/env bash

set -e
set -o pipefail

declare -i retval=0

{
	printf "Running: %s\n" "ansible ${1} -m ping"
	printf "\n"
} >&2

ansible "${1}" -m ping | sed -r -e "s:^${1} .* => ::g"
retval=$? # hmm, it's always 0
printf "\n" >&2

{
	printf "Success: "
	if [[ ${retval} -eq 0 ]]; then
		printf "true"
	else
		printf "false"
	fi
	printf "\n"
} >&2

exit ${retval}
