---
# Setup 1password
# https://support.1password.com/install-linux/#get-1password-for-linux
# https://support.1password.com/betas/#install-a-beta-release-of-1password-for-linux
- name: Ensure 1password packages are installed
  hosts: all
  become: true
  vars:
    deb_architecture:
      aarch64: "arm64"
      x86_64: "amd64"
    this_arch: "{{ [ansible_architecture] | map('extract', deb_architecture) | first }}"
  tasks:
    - name: Setup 1password
      block:
        - name: 1password-Repo | add apt-keyring
          ansible.builtin.get_url:
            dest: /usr/share/keyrings/1password-archive-keyring.asc
            url: https://downloads.1password.com/linux/keys/1password.asc
            checksum: sha256:145d6a930ec0326bbcff0db68111ccafe2a07222b4fd32ff6c717b9fba34708b
            mode: "0444"
        - name: 1password-Repo | add debsig dir
          ansible.builtin.file:
            path: /etc/debsig/policies/AC2D62742012EA22
            state: directory
            mode: "0555"
        - name: 1password-Repo | add apt-keyring
          ansible.builtin.get_url:
            dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
            url: https://downloads.1password.com/linux/debian/debsig/1password.pol
            mode: "0444"
        - name: 1password-Repo | add apt-source
          ansible.builtin.apt_repository:
            state: present
            repo: "deb [arch={{ this_arch }} signed-by=/usr/share/keyrings/1password-archive-keyring.asc] https://downloads.1password.com/linux/debian/{{ this_arch }} stable main"
            filename: 1password
        - name: 1password-Repo | install packages
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
            update_cache: true
          with_items:
            - 1password-cli
    - name: 1password update
      ansible.builtin.command:
      args:
        cmd: "op update"
      register: output
      changed_when: "'using the latest stable version' not in output.stdout"
