---
# Setup Golang
# https://go.dev/doc/install
# https://go.dev/wiki/GOPATH
- name: Ensure the latest Golang tools are installed
  hosts: all
  become: true
  environment:
    GOROOT: "{{ goroot }}"
    GOPATH: "{{ gopath }}"
    GOBIN: "{{ gopath }}/bin"
    GOSRC: "{{ gopath }}/src"
    PATH: "{{ gopath }}/bin:{{ goroot }}/bin:{{ ansible_env.PATH }}"
  vars:
    goroot: /usr/local/go
    gopath: /usr/local/golang
    golang_architecture:
      aarch64: "arm64"
      x86_64: "amd64"
  tags:
    - packages
    - raspberrypi
    - raspianos
    - golang
    - cleanup
  tasks:
    - name: Remove old Golang on Debian
      when: ansible_distribution == "Debian"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        update_cache: true
      with_items:
        - golang
        - golang-any
        - golang-go
        - golang-doc
        - golang-src
        - golang-1.19
        - golang-1.19-doc
        - golang-1.19-go
        - golang-1.19-src
    - name: Install Golang dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
      with_items:
        - libssl-dev
    - name: Add /etc/profile.d/golang.sh
      ansible.builtin.copy:
        dest: /etc/profile.d/golang.sh
        content: |
          export GOROOT="{{ goroot }}"
          export GOPATH="{{ gopath }}"
          export GOBIN="${GOPATH}/bin"
          export GOSRC="${GOPATH}/src"
          PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"
        mode: "0644"
    - name: Install golang installer
      ansible.builtin.copy:
        src: "{{ source_path }}"
        dest: /usr/local/bin/golang-setup
        mode: "0755"
      vars:
        source_path: "../files/installers/golang-setup"
    - name: Run Golang installer
      ansible.builtin.command: /usr/local/bin/golang-setup
      args:
        creates: "{{ gopath }}/bin/go"
    - name: Ensure golang packages are installed
      block:
        - name: Install via golang part
          ansible.builtin.command: go install "{{ item.url }}@latest"
          with_items:
            - {url: github.com/AlekSi/gocov-xml, bin: gocov-xml}
            - {url: github.com/BurntSushi/go-sumtype, bin: go-sumtype}
            - {url: github.com/GoogleCloudPlatform/govanityurls, bin: govanityurls}
            - {url: github.com/appliedgocode/goman, bin: goman}
            - {url: github.com/axw/gocov/gocov, bin: gocov}
            - {url: github.com/bwplotka/bingo, bin: bingo}
            - {url: github.com/charmbracelet/gum, bin: gum}
            - {url: github.com/client9/misspell/cmd/misspell, bin: misspell}
            - {url: github.com/create-go-app/cli/v3/cmd/cgapp, bin: cgapp}
            - {url: github.com/daixiang0/gci, bin: gci}
            - {url: github.com/dave/courtney, bin: courtney}
            - {url: github.com/davidrjenni/reftools/cmd/fillstruct, bin: fillstruct}
            - {url: github.com/davidrjenni/reftools/cmd/fillswitch, bin: fillswitch}
            - {url: github.com/davidrjenni/reftools/cmd/fixplurals, bin: fixplurals}
            - {url: github.com/dundee/gdu/v5/cmd/gdu, bin: gdu}
            - {url: github.com/fatih/gomodifytags, bin: gomodifytags}
            - {url: github.com/fatih/motion, bin: motion}
            - {url: github.com/foxboron/sbctl/cmd/sbctl, bin: sbctl}
            - {url: github.com/fzipp/gocyclo/cmd/gocyclo, bin: gocyclo}
            - {url: github.com/get-woke/woke, bin: woke}
            - {url: github.com/go-critic/go-critic/cmd/gocritic, bin: gocritic}
            - {url: github.com/go-delve/delve/cmd/dlv, bin: dlv}
            - {url: github.com/godoctor/godoctor, bin: godoctor}
            - {url: github.com/gokrazy/tools/cmd/gok, bin: gok}
            - {url: github.com/golangci/golangci-lint/cmd/golangci-lint, bin: golangci-lint}
            - {url: github.com/google/go-licenses, bin: go-licenses}
            - {url: github.com/google/wire/cmd/wire, bin: wire}
            - {url: github.com/google/yamlfmt/cmd/yamlfmt, bin: yamlfmt}
            - {url: github.com/gordonklaus/ineffassign, bin: ineffassign}
            - {url: github.com/goreleaser/goreleaser, bin: goreleaser}
            - {url: github.com/govim/govim/cmd/govim, bin: govim}
            - {url: github.com/grafana/jsonnet-language-server, bin: jsonnet-language-server}
            - {url: github.com/haya14busa/goplay/cmd/goplay, bin: goplay}
            - {url: github.com/jandelgado/gcov2lcov, bin: gcov2lcov}
            - {url: github.com/jesseduffield/lazygit, bin: lazygit}
            - {url: github.com/josharian/impl, bin: impl}
            - {url: github.com/jstemmer/gotags, bin: gotags}
            - {url: github.com/kisielk/errcheck, bin: errcheck}
            - {url: github.com/klauspost/asmfmt/cmd/asmfmt, bin: asmfmt}
            - {url: github.com/koron/iferr, bin: iferr}
            - {url: github.com/magefile/mage, bin: mage}
            - {url: github.com/maruel/panicparse/v2/cmd/pp, bin: pp}
            - {url: github.com/mattn/goveralls, bin: goveralls}
            - {url: github.com/mgechev/revive, bin: revive}
            - {url: github.com/motemen/go-iferr/cmd/goiferr, bin: goiferr}
            - {url: github.com/pelletier/go-toml/v2/cmd/jsontoml, bin: jsontoml}
            - {url: github.com/pelletier/go-toml/v2/cmd/tomljson, bin: tomljson}
            - {url: github.com/pelletier/go-toml/v2/cmd/tomll, bin: tomll}
            - {url: github.com/princjef/gomarkdoc/cmd/gomarkdoc, bin: gomarkdoc}
            - {url: github.com/quasilyte/go-consistent, bin: go-consistent}
            - {url: github.com/rakyll/gotest, bin: gotest}
            - {url: github.com/ramya-rao-a/go-outline, bin: go-outline}
            - {url: github.com/remotemobprogramming/mob/v3, bin: mob}
            - {url: github.com/rhysd/actionlint/cmd/actionlint, bin: actionlint}
            - {url: github.com/rogpeppe/godef, bin: godef}
            - {url: github.com/schmichael/gostack/cmd/gstack, bin: gstack}
            - {url: github.com/securego/gosec/v2/cmd/gosec, bin: gosec}
            - {url: github.com/securego/gosec/v2/cmd/gosecutil, bin: gosecutil}
            - {url: github.com/securego/gosec/v2/cmd/tlsconfig, bin: tlsconfig}
            - {url: github.com/segmentio/golines, bin: golines}
            - {url: github.com/spf13/cobra-cli, bin: cobra-cli}
            - {url: github.com/sqs/goreturns, bin: goreturns}
            - {url: github.com/t-yuki/gocover-cobertura, bin: gocover-cobertura}
            - {url: github.com/viktomas/godu, bin: godu}
            - {url: golang.org/x/lint/golint, bin: golint}
            - {url: golang.org/x/perf/cmd/benchstat, bin: benchstat}
            - {url: golang.org/x/tools/cmd/cover, bin: cover}
            - {url: golang.org/x/tools/cmd/present, bin: present}
            - {url: golang.org/x/tools/gopls, bin: gopls}
            - {url: golang.org/x/vuln/cmd/govulncheck, bin: govulncheck}
            - {url: google.golang.org/grpc/cmd/protoc-gen-go-grpc, bin: protoc-gen-go-grpc}
            - {url: google.golang.org/protobuf/cmd/protoc-gen-go, bin: protoc-gen-go}
            - {url: honnef.co/go/tools/cmd/keyify, bin: keyify}
            - {url: honnef.co/go/tools/cmd/staticcheck, bin: staticcheck}
            - {url: mvdan.cc/garble, bin: garble}
            - {url: mvdan.cc/gofumpt, bin: gofumpt}
            - {url: mvdan.cc/sh/v3/cmd/shfmt, bin: shfmt}
          args:
            creates: "{{ ansible_env.GOPATH }}/bin/{{ item.bin }}"
