---
# Setup Golang
# https://go.dev/doc/install
# https://go.dev/wiki/GOPATH
- name: Ensure the latest Golang tools are installed
  hosts: all
  become: true
  environment:
    GOROOT: "{{ goroot }}"
    GOPATH: "{{ gopath }}"
    GOBIN: "{{ gopath }}/bin"
    GOSRC: "{{ gopath }}/src"
    PATH: "{{ gopath }}/bin:{{ goroot }}/bin:{{ ansible_env.PATH }}"
  vars:
    goroot: /usr/local/go
    gopath: /usr/local/golang
    golang_architecture:
      aarch64: "arm64"
      x86_64: "amd64"
  tags:
    - packages
    - raspberrypi
    - raspianos
    - golang
    - cleanup
  tasks:
    - name: Remove old Golang on Debian
      when: ansible_distribution == "Debian"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        update_cache: true
      with_items:
        - golang
        - golang-any
        - golang-go
        - golang-doc
        - golang-src
        - golang-1.19
        - golang-1.19-doc
        - golang-1.19-go
        - golang-1.19-src
    - name: Install Golang dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
      with_items:
        - libssl-dev
    - name: Add /etc/profile.d/golang.sh
      ansible.builtin.copy:
        dest: /etc/profile.d/golang.sh
        content: |
          export GOROOT="{{ goroot }}"
          export GOPATH="{{ gopath }}"
          export GOBIN="${GOPATH}/bin"
          export GOSRC="${GOPATH}/src"
          PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"
        mode: "0644"
    - name: Install golang installer
      ansible.builtin.copy:
        src: "{{ source_path }}"
        dest: /usr/local/bin/golang-setup
        mode: "0755"
      vars:
        source_path: "../files/installers/golang-setup"
    - name: Run Golang installer
      ansible.builtin.command: /usr/local/bin/golang-setup
      args:
        creates: "{{ gopath }}/bin/go"
    - name: Add /usr/local/golang/bin/go
      ansible.builtin.copy:
        src: "{{ source_path }}"
        dest: /usr/local/golang/bin/go
        mode: "0755"
      vars:
        source_path: "../files/bin/go"
    - name: Ensure golang packages are installed
      block:
        - name: Install tools via golang
          ansible.builtin.command: go install "{{ item }}@latest"
          with_items:
            - github.com/AlekSi/gocov-xml
            - github.com/BurntSushi/go-sumtype
            - github.com/GoogleCloudPlatform/govanityurls
            - github.com/appliedgocode/goman
            - github.com/axw/gocov/gocov
            - github.com/bwplotka/bingo
            - github.com/charmbracelet/gum
            - github.com/client9/misspell/cmd/misspell
            - github.com/create-go-app/cli/v3/cmd/cgapp
            - github.com/daixiang0/gci
            - github.com/dave/courtney
            - github.com/davidrjenni/reftools/cmd/fillstruct
            - github.com/davidrjenni/reftools/cmd/fillswitch
            - github.com/davidrjenni/reftools/cmd/fixplurals
            - github.com/dundee/gdu/v5/cmd/gdu
            - github.com/fatih/gomodifytags
            - github.com/fatih/motion
            - github.com/foxboron/sbctl/cmd/sbctl
            - github.com/fzipp/gocyclo/cmd/gocyclo
            - github.com/get-woke/woke
            - github.com/go-critic/go-critic/cmd/gocritic
            - github.com/go-delve/delve/cmd/dlv
            - github.com/godoctor/godoctor
            - github.com/gokrazy/tools/cmd/gok
            - github.com/golangci/golangci-lint/cmd/golangci-lint
            - github.com/google/go-licenses
            - github.com/google/wire/cmd/wire
            - github.com/google/yamlfmt/cmd/yamlfmt
            - github.com/gordonklaus/ineffassign
            - github.com/goreleaser/goreleaser
            - github.com/govim/govim/cmd/govim
            - github.com/grafana/jsonnet-language-server
            - github.com/haya14busa/goplay/cmd/goplay
            - github.com/jandelgado/gcov2lcov
            - github.com/jesseduffield/lazygit
            - github.com/josharian/impl
            - github.com/jstemmer/gotags
            - github.com/kisielk/errcheck
            - github.com/klauspost/asmfmt/cmd/asmfmt
            - github.com/koron/iferr
            - github.com/magefile/mage
            - github.com/maruel/panicparse/v2/cmd/pp
            - github.com/mattn/goveralls
            - github.com/mgechev/revive
            - github.com/motemen/go-iferr/cmd/goiferr
            - github.com/pelletier/go-toml/v2/cmd/jsontoml
            - github.com/pelletier/go-toml/v2/cmd/tomljson
            - github.com/pelletier/go-toml/v2/cmd/tomll
            - github.com/princjef/gomarkdoc/cmd/gomarkdoc
            - github.com/quasilyte/go-consistent
            - github.com/rakyll/gotest
            - github.com/ramya-rao-a/go-outline
            - github.com/remotemobprogramming/mob/v3
            - github.com/rhysd/actionlint/cmd/actionlint
            - github.com/rogpeppe/godef
            - github.com/schmichael/gostack/cmd/gstack
            - github.com/securego/gosec/v2/cmd/gosec
            - github.com/securego/gosec/v2/cmd/gosecutil
            - github.com/securego/gosec/v2/cmd/tlsconfig
            - github.com/segmentio/golines
            - github.com/spf13/cobra-cli
            - github.com/sqs/goreturns
            - github.com/t-yuki/gocover-cobertura
            - github.com/viktomas/godu
            - golang.org/x/lint/golint
            - golang.org/x/perf/cmd/benchstat
            - golang.org/x/tools/cmd/cover
            - golang.org/x/tools/cmd/present
            - golang.org/x/tools/gopls
            - golang.org/x/vuln/cmd/govulncheck
            - google.golang.org/grpc/cmd/protoc-gen-go-grpc
            - google.golang.org/protobuf/cmd/protoc-gen-go
            - honnef.co/go/tools/cmd/staticcheck
            - honnef.co/go/tools/cmd/structlayout
            - honnef.co/go/tools/cmd/structlayout-optimize
            - honnef.co/go/tools/cmd/structlayout-pretty
            - mvdan.cc/garble
            - mvdan.cc/gofumpt
            - mvdan.cc/sh/v3/cmd/shfmt
          register: output
          changed_when: "'go: downloading' in output.stderr"
