---
# Setup LLVM
# https://apt.llvm.org/
- name: Ensure LLVM packages are installed
  hosts: all
  become: true
  vars:
    deb_architecture:
      aarch64: "arm64"
      x86_64: "amd64"
    llvm_ver: 18
  tasks:
    - name: Remove old LLVM on Debian
      tags:
        - packages
        - raspberrypi
        - raspianos
        - llvm
        - cleanup
      when: ansible_distribution == "Debian"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
        update_cache: true
      with_items:
        - llvm*
        - llvm-13*
        - llvm-14*
        - llvm-15*
        - llvm-16*
    - name: LLVM setup
      block:
        - name: LLVM setup | add apt-keyring
          ansible.builtin.get_url:
            dest: /etc/apt/keyrings/llvm.asc
            url: https://apt.llvm.org/llvm-snapshot.gpg.key
            mode: "0444"
        - name: LLVM setup | add apt-source
          ansible.builtin.apt_repository:
            state: present
            repo: "deb [arch={{ [ansible_architecture] | map('extract', deb_architecture) | first }} signed-by=/etc/apt/keyrings/llvm.asc] http://apt.llvm.org/{{ ansible_distribution_release }} {{ item }} main"
          with_items:
            - "llvm-toolchain-{{ ansible_distribution_release }}"
            - "llvm-toolchain-{{ ansible_distribution_release }}-17"
            - "llvm-toolchain-{{ ansible_distribution_release }}-18"
            - "llvm-toolchain-{{ ansible_distribution_release }}-19"
        - name: LLVM setup | install packages
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
            update_cache: true
          with_items:
            - "clang-{{ llvm_ver }}"
            - "clang-{{ llvm_ver }}-doc"
            - "clang-format-{{ llvm_ver }}"
            - "clang-tidy-{{ llvm_ver }}"
            - "clang-tools-{{ llvm_ver }}"
            - "clangd-{{ llvm_ver }}"
            - "libc++-{{ llvm_ver }}-dev"
            - "libc++abi-{{ llvm_ver }}-dev"
            - "libclang-{{ llvm_ver }}-dev"
            - "libclang-common-{{ llvm_ver }}-dev"
            - "libclang-rt-{{ llvm_ver }}-dev"
            - "libclang1-{{ llvm_ver }}"
            - "libclc-{{ llvm_ver }}-dev"
            - "libllvm-{{ llvm_ver }}-ocaml-dev"
            - "libllvm{{ llvm_ver }}"
            - "libomp-{{ llvm_ver }}-dev"
            - "libpolly-{{ llvm_ver }}-dev"
            - "libunwind-{{ llvm_ver }}-dev"
            - "lld-{{ llvm_ver }}"
            - "lldb-{{ llvm_ver }}"
            - "llvm-{{ llvm_ver }}"
            - "llvm-{{ llvm_ver }}-dev"
            - "llvm-{{ llvm_ver }}-doc"
            - "llvm-{{ llvm_ver }}-examples"
            - "llvm-{{ llvm_ver }}-runtime"
            - "python3-clang-{{ llvm_ver }}"
