---
# Setup tailscale
# davfs2 debconf: https://sources.debian.org/src/davfs2/1.7.0-1/debian/templates/
- name: Ensure tailscale packages are installed
  hosts: all
  become: true
  tasks:
    - name: Setup tailscale
      block:
        - name: Tailscale-Repo | add apt-keyring
          ansible.builtin.get_url:
            dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
            url: https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
            mode: "0444"
        - name: Tailscale-Repo | remove repo symlink
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          with_items:
            - /etc/apt/sources.list.d/pkgs_tailscale_com_stable_debian.list
            - /etc/apt/sources.list.d/tailscale.list
        - name: Tailscale-Repo | add apt-source
          ansible.builtin.apt_repository:
            state: present
            repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian bookworm main"
            filename: tailscale
        - name: Tailscale-Repo | install packages
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
            update_cache: true
          with_items:
            - tailscale
    - name: Tailscale update
      ansible.builtin.command:
      args:
        cmd: "tailscale update"
      register: output
      changed_when: "'already running stable version' not in output.stdout"
    - name: Setup davfs2
      block:
        - name: Davfs-Setup | install packages
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
            update_cache: true
          with_items:
            - davfs2
        - name: Davfs-Setup | debconf get
          ansible.builtin.debconf:
            name: "{{ item }}"
          with_items:
            - davfs2
        - name: Davfs-Setup | debconf set
          ansible.builtin.debconf:
            name: "{{ item.pkg }}"
            question: "{{ item.question }}"
            vtype: "{{ item.vtype }}"
            value: "{{ item.answer }}"
            unseen: false
          with_items:
            - {pkg: "davfs2", question: "davfs2/suid_file", vtype: "boolean", answer: false}
            - {pkg: "davfs2", question: "davfs2/user_name", vtype: "string", answer: "davfs2"}
            - {pkg: "davfs2", question: "davfs2/group_name", vtype: "string", answer: "davfs2"}
            - {pkg: "davfs2", question: "davfs2/new_user", vtype: "boolean", answer: true}
            - {pkg: "davfs2", question: "davfs2/new_group", vtype: "boolean", answer: true}
